### ISSUE TITLE
Minor Suggestion: Rename Tutorials link

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast-docs#127]
A first coming user to https://docs.hazelcast.com/ would click on the Tutorials directly and expect Tutorials to be about how to do simple stuff with pure Hazelcast.

But our Tutorials page is related to integration modules only. 

We could rename it "integration tutorials" or similar, and maybe put it afterwards "getting started" link?

**Comment by JakeSCahill** [comment]
Yeah I agree. @vladoschreiner @Serdaro what do you think?

**Comment by vladoschreiner** [comment]
Linked page (https://guides.hazelcast.org/home/) is only source we do have for tutorials. So we should add basic tutorials to that page rather than renaming the link.

**Comment by sertugkaya** [comment]
Sounds better. Is there a task for creating basic tutorials?

**Comment by JakeSCahill** [comment]
We've started adding basic tutorials there and will continue to use it for new tutorials.
